"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { usePathname } from "next/navigation";

export type Locale = "en" | "fr";

const STORAGE_KEY = "buildcheck-language";

const french: Record<string, string> = {
  // Shared navigation and actions
  "Dashboard": "Tableau de bord",
  "Discover": "Découvrir",
  "Demo": "Démo",
  "Validate": "Valider",
  "Projects": "Projets",
  "Reports": "Rapports",
  "Agents": "Agents",
  "Settings": "Paramètres",
  "Workspace": "Espace de travail",
  "Validate an idea": "Valider une idée",
  "Roast my idea": "Challenger mon idée",
  "Demo workspace": "Espace de démonstration",
  "Builder · demo account": "Builder · compte de démonstration",
  "Signals are simulated": "Les signaux sont simulés",
  "Analyze": "Analyser",
  "Primary navigation": "Navigation principale",
  "Mobile navigation": "Navigation mobile",
  "Log out": "Se déconnecter",
  "Toggle light or dark mode": "Basculer entre les modes clair et sombre",
  "Create account": "Créer un compte",
  "Reset password": "Réinitialiser le mot de passe",
  "Project analysis": "Analyse du projet",
  "Stop building SaaS nobody wants": "Arrêtez de créer des SaaS dont personne ne veut",

  // Common labels and enum presentation
  "Overview": "Vue d’ensemble",
  "Evidence": "Preuves",
  "Competition": "Concurrence",
  "Distribution": "Distribution",
  "Pivots": "Pivots",
  "Token ROI": "ROI des tokens",
  "Roast": "Challenge",
  "History": "Historique",
  "BUILD": "CONSTRUIRE",
  "VALIDATE FIRST": "VALIDER D’ABORD",
  "PIVOT": "PIVOTER",
  "KILL": "ABANDONNER",
  "Build": "Construire",
  "Pivot": "Pivoter",
  "Killed": "Abandonnées",
  "Archived": "Archivées",
  "All": "Toutes",
  "Low": "Faible",
  "Medium": "Moyenne",
  "High": "Élevée",
  "Very high": "Très élevée",
  "Strong": "Fort",
  "Weak": "Faible",
  "moderate": "modéré",
  "strong": "fort",
  "weak": "faible",
  "High intensity": "Forte intensité",
  "Medium intensity": "Intensité moyenne",
  "Low intensity": "Faible intensité",
  "read": "lecture",
  "write": "écriture",
  "success": "succès",
  "error": "erreur",
  "active": "actif",
  "adapter planned": "adaptateur prévu",
  "available · server opt-in": "disponible · activation côté serveur",
  "available · feed config required": "disponible · configuration des flux requise",
  "not connected": "non connecté",

  // Marketing
  "Product": "Produit",
  "Method": "Méthode",
  "Methodology": "Méthodologie",
  "Marketing navigation": "Navigation du site",
  "Sign in": "Se connecter",
  "Open demo": "Ouvrir la démo",
  "Built for humans and AI agents": "Conçu pour les humains et les agents IA",
  "Stop building SaaS": "Arrêtez de créer des SaaS",
  "nobody wants.": "dont personne ne veut.",
  "BuildCheck validates demand, competition and distribution before you — or your coding agent — spend weeks building the wrong product.": "BuildCheck valide la demande, la concurrence et la distribution avant que vous — ou votre agent de code — ne passiez des semaines à créer le mauvais produit.",
  "Analyze my idea": "Analyser mon idée",
  "Explore opportunities": "Explorer les opportunités",
  "BuildCheck dashboard preview": "Aperçu du tableau de bord BuildCheck",
  "InvoiceFlow analysis": "Analyse d’InvoiceFlow",
  "Evidence says: validate the wedge.": "Les preuves disent : validez votre angle d’attaque.",
  "Score breakdown": "Détail du score",
  "Demand": "Demande",
  "Pain": "Douleur",
  "Minimum testable version": "Version minimale testable",
  "Sell the outcome first.": "Vendez d’abord le résultat.",
  "Focused landing page": "Landing page ciblée",
  "3 paid pilots": "3 pilotes payants",
  "Manual delivery": "Livraison manuelle",
  "The pre-build layer": "La couche d’avant-construction",
  "Your coding agent can code. But should it?": "Votre agent sait coder. Mais devrait-il le faire ?",
  "Give your coding agent permission to say no — or to propose the smallest validation MVP worth building first.": "Donnez à votre agent de code la permission de dire non — ou de proposer le plus petit MVP de validation qui mérite d’être construit.",
  "User intent": "Intention utilisateur",
  "Step": "Étape",
  "Coding agent": "Agent de code",
  "BuildCheck": "BuildCheck",
  "Build / Validate / Pivot / Kill": "Construire / Valider / Pivoter / Abandonner",
  "Code the minimum next action": "Coder la prochaine action minimale",
  "Explore WebMCP site tools": "Explorer les outils WebMCP du site",
  "One decision system": "Un système de décision unique",
  "Your AI knows how to code. BuildCheck tells it what’s worth coding.": "Votre IA sait coder. BuildCheck lui indique ce qui mérite de l’être.",
  "See the market case, the failure case and the cheapest validation test in one explainable report.": "Retrouvez l’opportunité marché, le scénario d’échec et le test de validation le moins coûteux dans un rapport explicable.",
  "Evidence, not vibes": "Des preuves, pas des impressions",
  "Separate observable signals from interpretation. Every score points back to its evidence.": "Séparez les signaux observables de leur interprétation. Chaque score renvoie à ses preuves.",
  "Deterministic Build Score": "Build Score déterministe",
  "Demand, pain, pricing, distribution, competition, simplicity and defensibility — weighted in code.": "Demande, douleur, prix, distribution, concurrence, simplicité et défendabilité — pondérés dans le code.",
  "Roast before you build": "Challengez avant de construire",
  "Attack weak assumptions and define exactly what evidence would change the verdict.": "Attaquez les hypothèses fragiles et définissez précisément quelles preuves changeraient le verdict.",
  "Discover real problems": "Découvrez de vrais problèmes",
  "Start from repeated frustrations and costly workarounds, not a solution looking for a market.": "Partez de frustrations récurrentes et de contournements coûteux, pas d’une solution en quête de marché.",
  "Protect your tokens": "Protégez vos tokens",
  "Estimate implementation cost and shrink the idea into a test you can run this afternoon.": "Estimez le coût d’implémentation et réduisez l’idée à un test exécutable dès cet après-midi.",
  "Built for AI-native builders": "Conçu pour les builders natifs IA",
  "Service boundaries are ready for a future MCP without coupling product logic to the UI.": "Les frontières de services sont prêtes pour un futur MCP sans coupler la logique produit à l’interface.",
  "Demo workspace included": "Espace de démonstration inclus",
  "Kill weak ideas before they kill your roadmap.": "Abandonnez les idées faibles avant qu’elles ne sabotent votre roadmap.",
  "No API key required. The demo uses a transparent, curated dataset and the same deterministic scoring engine as future live-source analyses.": "Aucune clé API requise. La démo utilise un jeu de données transparent et sélectionné, ainsi que le même moteur de score déterministe que les futures analyses de sources réelles.",
  "Try the full product": "Essayer le produit complet",
  "Demo evidence is clearly labeled. No market data is invented by an LLM.": "Les preuves de démonstration sont clairement identifiées. Aucune donnée marché n’est inventée par un LLM.",
  "Back": "Retour",
  "A score you can disagree with — and inspect.": "Un score que vous pouvez contester — et inspecter.",
  "BuildCheck separates evidence collection, interpretation and scoring so an AI provider can never manufacture market proof or choose the final number.": "BuildCheck sépare la collecte des preuves, leur interprétation et le calcul du score afin qu’un fournisseur IA ne puisse jamais fabriquer de preuve marché ni choisir la note finale.",
  "1. Collect": "1. Collecter",
  "A DataSourceProvider returns explicit market signals, competitors and channels. In V1, every record comes from a curated demo scenario and is marked isDemo=true.": "Un DataSourceProvider renvoie des signaux marché, des concurrents et des canaux explicites. Dans la V1, chaque donnée provient d’un scénario de démonstration sélectionné et porte le marqueur isDemo=true.",
  "2. Interpret": "2. Interpréter",
  "An AIProvider may structure the idea, classify supplied signals and draft recommendations. With no signals, it must return Not enough evidence.": "Un AIProvider peut structurer l’idée, classer les signaux fournis et rédiger des recommandations. Sans signal, il doit renvoyer Pas assez de preuves.",
  "3. Score": "3. Noter",
  "Pure TypeScript functions score seven dimensions: Demand 25, Pain 20, Willingness to pay 15, Distribution 15, Competition gap 10, Build simplicity 10 and Defensibility 5.": "Des fonctions TypeScript pures évaluent sept dimensions : Demande 25, Douleur 20, Propension à payer 15, Distribution 15, Espace concurrentiel 10, Simplicité de construction 10 et Défendabilité 5.",
  "4. Decide": "4. Décider",
  "Code maps 80–100 to BUILD, 60–79 to VALIDATE FIRST, 40–59 to PIVOT and 0–39 to KILL. Confidence is calculated separately from evidence coverage and quality.": "Le code associe 80–100 à CONSTRUIRE, 60–79 à VALIDER D’ABORD, 40–59 à PIVOTER et 0–39 à ABANDONNER. La confiance est calculée séparément selon la couverture et la qualité des preuves.",
  "Demo data policy": "Politique des données de démonstration",
  "No live-source claims.": "Aucune fausse promesse de source réelle.",
  "Names such as “Demo interview”, “Demo app review” and “Demo pricing study” describe scenario categories, not completed research. Quotes in the UI are product-writing examples. They must be replaced record by record as compliant providers are connected.": "Les noms comme « Entretien démo », « Avis d’application démo » et « Étude de prix démo » décrivent des catégories de scénario, pas des recherches réalisées. Les citations de l’interface sont des exemples de rédaction produit. Elles doivent être remplacées donnée par donnée à mesure que des fournisseurs conformes sont connectés.",
  "Run a demo analysis": "Lancer une analyse de démonstration",

  // Authentication and onboarding
  "Build less. Learn faster.": "Construisez moins. Apprenez plus vite.",
  "The most valuable feature may be the one you never build.": "La fonctionnalité la plus précieuse est peut-être celle que vous ne construirez jamais.",
  "BuildCheck turns assumptions into evidence, scores and a minimum test.": "BuildCheck transforme les hypothèses en preuves, en scores et en test minimal.",
  "Demo workspace · External lookups require consent": "Espace de démonstration · Les recherches externes nécessitent votre consentement",
  "Welcome back": "Ravi de vous revoir",
  "Make the next idea earn its roadmap.": "Faites mériter sa place à votre prochaine idée.",
  "Any valid demo credentials work locally.": "Tout identifiant de démonstration valide fonctionne localement.",
  "Email": "E-mail",
  "Password": "Mot de passe",
  "Forgot password?": "Mot de passe oublié ?",
  "Enter an email and a password of at least 6 characters.": "Saisissez un e-mail et un mot de passe d’au moins 6 caractères.",
  "New to BuildCheck?": "Nouveau sur BuildCheck ?",
  "Create a demo account": "Créer un compte de démonstration",
  "Create workspace": "Créer un espace",
  "Decide what deserves to exist.": "Décidez de ce qui mérite d’exister.",
  "Demo signup stays on this device. Supabase Auth is represented in the migration, but not connected.": "L’inscription de démonstration reste sur cet appareil. Supabase Auth est prévu dans la migration, mais n’est pas connecté.",
  "First name": "Prénom",
  "8 characters minimum": "8 caractères minimum",
  "Continue": "Continuer",
  "Already have an account?": "Vous avez déjà un compte ?",
  "Check your inbox.": "Consultez votre boîte de réception.",
  "Demo mode does not send email. In production, Supabase Auth would issue a one-time recovery link.": "Le mode démo n’envoie pas d’e-mail. En production, Supabase Auth émettrait un lien de récupération à usage unique.",
  "Back to sign in": "Retour à la connexion",
  "Account recovery": "Récupération du compte",
  "Reset your password.": "Réinitialisez votre mot de passe.",
  "Enter the email attached to your workspace.": "Saisissez l’e-mail associé à votre espace.",
  "Send recovery link": "Envoyer le lien de récupération",
  "Onboarding": "Configuration",
  "of": "sur",
  "What’s your main goal?": "Quel est votre objectif principal ?",
  "This tunes the opportunity feed and recommendations.": "Cela personnalise le flux d’opportunités et les recommandations.",
  "Open workspace": "Ouvrir l’espace",
  "Mobile apps": "Applications mobiles",
  "AI tools": "Outils IA",
  "Chrome extensions": "Extensions Chrome",
  "Developer tools": "Outils développeur",
  "Marketplaces": "Places de marché",
  "Other": "Autre",
  "Find ideas": "Trouver des idées",
  "Validate my ideas": "Valider mes idées",
  "Avoid wasting time": "Éviter de perdre du temps",
  "Find better niches": "Trouver de meilleures niches",
  "Build faster": "Construire plus vite",

  // Dashboard
  "Decision workspace": "Espace de décision",
  "Good morning": "Bonjour",
  "Five ideas on the table. Only the evidence gets a vote.": "Cinq idées sur la table. Seules les preuves ont voix au chapitre.",
  "Ideas analyzed": "Idées analysées",
  "Across this demo workspace": "Dans cet espace de démonstration",
  "Build candidates": "Idées candidates à la construction",
  "Score ≥ 80": "Score ≥ 80",
  "Ideas killed": "Idées abandonnées",
  "Score below 40": "Score inférieur à 40",
  "Average Build Score": "Build Score moyen",
  "Weighted, not AI-generated": "Pondéré, non généré par l’IA",
  "Workspace statistics": "Statistiques de l’espace",
  "Recent projects": "Projets récents",
  "Latest analysis for every active idea": "Dernière analyse de chaque idée active",
  "View all": "Tout afficher",
  "Opportunities for you": "Opportunités pour vous",
  "Curated demo dataset": "Jeu de données de démonstration sélectionné",
  "Token economics": "Économie de tokens",
  "estimated coding tokens protected": "tokens de code estimés préservés",
  "By deferring weak scopes and testing their riskiest assumption first. This is an implementation estimate, not provider billing data.": "En reportant les périmètres fragiles et en testant d’abord leur hypothèse la plus risquée. Il s’agit d’une estimation d’implémentation, pas de données de facturation d’un fournisseur.",

  // Discover
  "Start with pain, not a pitch.": "Partez de la douleur, pas d’un pitch.",
  "Explore recurring problems with testable audiences, pricing hypotheses and implementation constraints.": "Explorez des problèmes récurrents avec des audiences testables, des hypothèses de prix et des contraintes d’implémentation.",
  "Curated demo feed": "Flux de démonstration sélectionné",
  "Opportunity filters": "Filtres d’opportunités",
  "All categories": "Toutes les catégories",
  "Any complexity": "Toute complexité",
  "Any competition": "Toute concurrence",
  "Any score": "Tout score",
  "Category": "Catégorie",
  "Complexity": "Complexité",
  "Minimum score": "Score minimal",
  "Pain score": "Score de douleur",
  "complaints": "plaintes",
  "requests": "demandes",
  "competitors": "concurrents",
  "POTENTIAL PRICING": "PRIX POTENTIEL",
  "Explore": "Explorer",
  "No opportunities match": "Aucune opportunité ne correspond",
  "Broaden one of the filters. The demo feed contains four carefully documented opportunities.": "Élargissez l’un des filtres. Le flux de démonstration contient quatre opportunités soigneusement documentées.",
  "Clear filters": "Effacer les filtres",
  "How opportunities are selected": "Comment les opportunités sont sélectionnées",
  "Repeated pain + reachable audience + affordable test.": "Douleur récurrente + audience accessible + test abordable.",
  "Opportunity scores are seeded for this feed and kept separate from project Build Scores. Live discovery providers are not connected.": "Les scores d’opportunité sont prédéfinis pour ce flux et restent distincts des Build Scores des projets. Les fournisseurs de découverte en direct ne sont pas connectés.",

  // Projects and reports
  "Your idea portfolio.": "Votre portefeuille d’idées.",
  "Keep every decision, score and re-analysis in one place.": "Conservez chaque décision, score et réanalyse au même endroit.",
  "New analysis": "Nouvelle analyse",
  "Search projects": "Rechercher des projets",
  "BUILD SCORE": "BUILD SCORE",
  "Build score": "Build Score",
  "out of 100": "sur 100",
  "CONFIDENCE": "CONFIANCE",
  "No projects here": "Aucun projet ici",
  "There are no ideas matching this status and search query.": "Aucune idée ne correspond à ce statut et à cette recherche.",
  "Show all projects": "Afficher tous les projets",
  "Every analysis, still explainable.": "Chaque analyse reste explicable.",
  "Review past decisions and print browser-ready reports. PDF export comes after the product workflow is validated.": "Consultez les décisions passées et imprimez des rapports prêts pour le navigateur. L’export PDF viendra après validation du parcours produit.",
  "Print list": "Imprimer la liste",
  "No reports yet": "Aucun rapport pour le moment",
  "Analyze your first idea to create a versioned report.": "Analysez votre première idée pour créer un rapport versionné.",
  "Analyze an idea": "Analyser une idée",
  "Describe the idea in at least 20 characters.": "Décrivez l’idée en au moins 20 caractères.",
  "Check the form and try again.": "Vérifiez le formulaire et réessayez.",
  "Understanding your idea": "Compréhension de votre idée",
  "Loading market signals": "Chargement des signaux marché",
  "Mapping competitors": "Cartographie des concurrents",
  "Analyzing user pain": "Analyse de la douleur utilisateur",
  "Evaluating distribution": "Évaluation de la distribution",
  "Estimating build complexity": "Estimation de la complexité de construction",
  "Calculating Build Score": "Calcul du Build Score",
  "Preparing recommendations": "Préparation des recommandations",
  "Deterministic demo analysis": "Analyse de démonstration déterministe",
  "Live source queries are running with strict timeouts. Partial results stay live; total failure falls back to clearly labeled demo evidence.": "Les requêtes vers les sources réelles s’exécutent avec des délais stricts. Les résultats partiels restent réels ; un échec total bascule vers des preuves de démonstration clairement identifiées.",
  "The mock providers return immediately; this short sequence exposes the worker-ready pipeline without pretending to contact live sources.": "Les fournisseurs mockés répondent immédiatement ; cette courte séquence rend visible le pipeline prêt pour un worker sans prétendre contacter des sources réelles.",
  "Adversarial mode": "Mode contradictoire",
  "Let’s try to kill this idea.": "Essayons de démonter cette idée.",
  "What are you thinking of building?": "Que pensez-vous construire ?",
  "Form detail mode": "Niveau de détail du formulaire",
  "Simple": "Simple",
  "Detailed": "Détaillé",
  "Describe your idea in plain English": "Décrivez votre idée simplement",
  "Example: A lightweight tool that automatically follows up unpaid invoices for freelance designers, without replacing their accounting software…": "Exemple : un outil léger qui relance automatiquement les factures impayées des designers freelances sans remplacer leur logiciel comptable…",
  "Include who it is for, the painful job and how you might charge.": "Précisez à qui elle s’adresse, le problème douloureux et votre mode de facturation envisagé.",
  "Project name": "Nom du projet",
  "optional": "facultatif",
  "Target customer": "Client cible",
  "Freelance design studios": "Studios de design freelances",
  "Describe your idea": "Décrivez votre idée",
  "What will the product do?": "Que fera le produit ?",
  "Problem being solved": "Problème résolu",
  "Late payments require awkward, repeated manual follow-up": "Les retards de paiement imposent des relances manuelles répétées et délicates",
  "How will it make money?": "Comment générera-t-il des revenus ?",
  "€19/month subscription": "Abonnement à 19 €/mois",
  "Existing competitors": "Concurrents existants",
  "Target geography": "Zone géographique ciblée",
  "France, Europe, Global…": "France, Europe, monde…",
  "Business model": "Modèle économique",
  "Website or competitor links": "Liens du site ou des concurrents",
  "Use live evidence from": "Utiliser les preuves réelles de",
  "Send up to three derived search keywords — not the full analysis — to": "Envoyer jusqu’à trois mots-clés de recherche dérivés — et non l’analyse complète — à",
  "Public evidence will be linked and marked observed.": "Les preuves publiques seront liées et marquées comme observées.",
  "8 public connectors": "8 connecteurs publics",
  "Apple App Store": "Apple App Store",
  "Stack Exchange": "Stack Exchange",
  "Mastodon": "Mastodon",
  "Bluesky": "Bluesky",
  "RSS/Atom feeds": "Flux RSS/Atom",
  "RSS/Atom": "RSS/Atom",
  "npm Registry": "Registre npm",
  "the configured public Mastodon instances": "les instances Mastodon publiques configurées",
  "the administrator-configured RSS hosts": "les hôtes RSS configurés par l’administrateur",
  "hn.algolia.com, api.github.com, api.stackexchange.com, itunes.apple.com, configured Mastodon/RSS hosts, public.api.bsky.app and registry.npmjs.org": "hn.algolia.com, api.github.com, api.stackexchange.com, itunes.apple.com, les hôtes Mastodon/RSS configurés, public.api.bsky.app et registry.npmjs.org",
  "Providers": "Fournisseurs",
  "live": "réel",
  "mock until consent": "mock jusqu’au consentement",
  "curated demo signals": "signaux de démonstration sélectionnés",
  "Roast mode on": "Mode challenge activé",
  "Roast this idea": "Challenger cette idée",
  "Analyze this idea": "Analyser cette idée",
  "Pressure-test the idea before the build.": "Mettez l’idée à l’épreuve avant de construire.",
  "Your description is structured and scored by deterministic functions, then matched to": "Votre description est structurée et notée par des fonctions déterministes, puis rapprochée de",
  "Your description is structured, matched to a transparent demo evidence set and scored by deterministic functions.": "Votre description est structurée, rapprochée d’un jeu transparent de preuves de démonstration et notée par des fonctions déterministes.",
  "observed": "discussions observées sur",
  "Hacker News and GitHub Issues discussions": "discussions Hacker News et GitHub Issues",
  "GitHub Issues discussions": "discussions GitHub Issues",
  "Hacker News discussions": "discussions Hacker News",
  "a transparent demo evidence set": "un jeu transparent de preuves de démonstration",
  "Only the configured public sources are queried. A partial failure keeps the remaining live evidence; total failure falls back to visibly marked demo data.": "Seules les sources publiques configurées sont interrogées. Un échec partiel conserve les preuves réelles restantes ; un échec total bascule vers des données de démonstration visiblement identifiées.",
  "Demo analyses never call Reddit, X, Google or an AI API. Evidence is simulated and visibly labeled.": "Les analyses de démonstration n’appellent jamais Reddit, X, Google ni une API d’IA. Les preuves sont simulées et clairement identifiées.",

  // Settings
  "Profile": "Profil",
  "Builder preferences": "Préférences de builder",
  "Language": "Langue",
  "AI provider": "Fournisseur IA",
  "Data sources": "Sources de données",
  "Notifications": "Notifications",
  "Billing": "Facturation",
  "Danger zone": "Zone sensible",
  "Settings sections": "Sections des paramètres",
  "Workspace configuration.": "Configuration de l’espace.",
  "Provider boundaries and demo limitations live here, away from the core product workflow.": "Les limites des fournisseurs et de la démo sont regroupées ici, à l’écart du parcours produit principal.",
  "Demo mode active": "Mode démo actif",
  "Used to personalize the decision workspace.": "Utilisé pour personnaliser l’espace de décision.",
  "Saved": "Enregistré",
  "Save profile": "Enregistrer le profil",
  "These guide future opportunity ranking.": "Ces choix guideront le classement futur des opportunités.",
  "What do you usually build?": "Que construisez-vous habituellement ?",
  "Primary product category": "Catégorie de produit principale",
  "Main goal": "Objectif principal",
  "What BuildCheck should optimize for": "Ce que BuildCheck doit optimiser",
  "Choose your interface language.": "Choisissez la langue de l’interface.",
  "The English version remains the default. Your choice is saved on this device.": "La version anglaise reste celle par défaut. Votre choix est enregistré sur cet appareil.",
  "Interface language": "Langue de l’interface",
  "English": "English",
  "French": "Français",
  "AI may structure or interpret supplied evidence. It never sets the final score or invents market proof.": "L’IA peut structurer ou interpréter les preuves fournies. Elle ne fixe jamais le score final et n’invente aucune preuve marché.",
  "server-side key required": "clé côté serveur requise",
  "no key required": "aucune clé requise",
  "Selected": "Sélectionné",
  "Mock provider": "Fournisseur mocké",
  "Hacker News via Algolia Search": "Hacker News via la recherche Algolia",
  "GitHub Issues via REST Search": "GitHub Issues via la recherche REST",
  "Stack Exchange API": "API Stack Exchange",
  "Apple App Store Search": "Recherche Apple App Store",
  "Mastodon public hashtags": "Hashtags publics Mastodon",
  "Bluesky public search": "Recherche publique Bluesky",
  "RSS/Atom configured feeds": "Flux RSS/Atom configurés",
  "npm public registry": "Registre public npm",
  "App & SaaS reviews": "Avis d’applications et de SaaS",
  "Not connected": "Non connecté",
  "Eight interchangeable public connectors are available server-side. This browser workspace remains mock-first until the server enables them and the user explicitly consents; RSS also requires administrator-selected feeds.": "Huit connecteurs publics interchangeables sont disponibles côté serveur. Cet espace navigateur reste mock-first tant que le serveur ne les active pas et que l’utilisateur ne donne pas explicitement son accord ; RSS exige aussi des flux choisis par l’administrateur.",
  "Default": "Par défaut",
  "Available": "Disponible",
  "Offline": "Hors ligne",
  "Notification delivery is local-only in demo mode.": "En mode démo, les notifications restent locales.",
  "Analysis complete": "Analyse terminée",
  "Notify when an asynchronous analysis finishes": "Notifier à la fin d’une analyse asynchrone",
  "Toggle analysis notifications": "Activer ou désactiver les notifications d’analyse",
  "Score changes": "Changements de score",
  "Alert when evidence changes a verdict": "Alerter lorsqu’une preuve modifie un verdict",
  "Toggle score change notifications": "Activer ou désactiver les alertes de score",
  "No payment provider is connected.": "Aucun fournisseur de paiement n’est connecté.",
  "Demo plan": "Offre de démonstration",
  "Unlimited local demo analyses · Curated signals · No external usage charges": "Analyses de démonstration locales illimitées · Signaux sélectionnés · Aucun coût d’usage externe",
  "Billing coming later": "Facturation à venir",
  "Reset only local browser data. Nothing is sent to a remote backend.": "Réinitialise uniquement les données locales du navigateur. Rien n’est envoyé à un backend distant.",
  "Reset demo workspace": "Réinitialiser l’espace de démonstration",
  "Restore the five seed projects and default profile": "Restaurer les cinq projets initiaux et le profil par défaut",
  "Resetting…": "Réinitialisation…",
  "Reset demo": "Réinitialiser la démo",
  "Delete account": "Supprimer le compte",
  "Unavailable because this is not a remote account": "Indisponible car il ne s’agit pas d’un compte distant",

  // Agents and WebMCP
  "Inspection failed": "Échec de l’inspection",
  "Give your coding agent permission to say no.": "Donnez à votre agent de code la permission de dire non.",
  "BuildCheck is the pre-build decision layer: should we build, what must we validate, and what is the smallest thing worth coding?": "BuildCheck est la couche de décision avant construction : faut-il construire, que faut-il valider et quelle est la plus petite chose qui mérite d’être codée ?",
  "Checking WebMCP…": "Vérification de WebMCP…",
  "WebMCP detected · registration unavailable": "WebMCP détecté · inscription indisponible",
  "WebMCP unavailable in this browser": "WebMCP indisponible dans ce navigateur",
  "Experimental open standard": "Standard ouvert expérimental",
  "Connect BuildCheck to the agent viewing this page.": "Connectez BuildCheck à l’agent qui consulte cette page.",
  "The native API is feature-detected. In a supported secure browser, the seven tools below are registered against this live page and current demo session. No remote MCP server is being simulated.": "L’API native document.modelContext est détectée selon les capacités du navigateur. Dans un navigateur sécurisé compatible, les sept outils ci-dessous sont inscrits sur cette page active et la session de démonstration en cours. Aucun serveur MCP distant n’est simulé.",
  "The native": "L’API native",
  "API is feature-detected. In a supported secure browser, the seven tools below are registered against this live page and current demo session. No remote MCP server is being simulated.": "est détectée selon les capacités du navigateur. Dans un navigateur sécurisé compatible, les sept outils ci-dessous sont inscrits sur cette page active et la session de démonstration en cours. Aucun serveur MCP distant n’est simulé.",
  "Pre-build agent flow": "Parcours de l’agent avant construction",
  "BuildCheck evidence": "Preuves BuildCheck",
  "Minimum code worth building": "Code minimal qui mérite d’être construit",
  "Challenge-ready setup": "Configuration prête pour le challenge",
  "Use the supported Site tools environment.": "Utilisez l’environnement compatible avec les outils du site.",
  "Use the latest ChatGPT desktop app with GPT-5.6 Sol or Terra. Keep Site tools enabled in Settings → Browser → Permissions.": "Utilisez la dernière version de l’app de bureau ChatGPT avec GPT-5.6 Sol ou Terra. Laissez les outils du site activés dans Réglages → Navigateur → Autorisations.",
  "7/7 tool contracts tested": "7/7 contrats d’outils testés",
  "Open this /agents page in the built-in browser": "Ouvrir cette page /agents dans le navigateur intégré",
  "Inspect Available site tools in the address bar": "Consulter les outils du site disponibles dans la barre d’adresse",
  "Run the demo prompt before allowing any code": "Lancer le prompt de démonstration avant d’autoriser le moindre code",
  "Availability still depends on the current OpenAI rollout and workspace type": "La disponibilité dépend encore du déploiement OpenAI en cours et du type d’espace de travail",
  "Available site tools": "Outils du site disponibles",
  "Narrow inputs, structured JSON outputs and explicit read/write annotations": "Entrées ciblées, sorties JSON structurées et annotations explicites de lecture/écriture",
  "Experimental WebMCP": "WebMCP expérimental",
  "Try the challenge story": "Tester le scénario du challenge",
  "One prompt, before any code.": "Un prompt, avant la moindre ligne de code.",
  "Open this deployed page in ChatGPT’s in-app browser, inspect Site tools in the address bar, then ask:": "Ouvrez cette page déployée dans le navigateur intégré de ChatGPT, consultez les outils du site dans la barre d’adresse, puis demandez :",
  "Should I build an AI CRM for freelancers? Use BuildCheck before writing code.": "Devrais-je construire un CRM IA pour les freelances ? Utilise BuildCheck avant d’écrire du code.",
  "Copied": "Copié",
  "Copy demo prompt": "Copier le prompt de démo",
  "Current boundary": "Limite actuelle",
  "Page-bound, not background MCP.": "Lié à la page, pas un MCP en arrière-plan.",
  "Requires a secure context and supported browser": "Nécessite un contexte sécurisé et un navigateur compatible",
  "Tools belong to the open page": "Les outils appartiennent à la page ouverte",
  "Demo state stays in this browser": "L’état de démonstration reste dans ce navigateur",
  "Supabase continuity is schema-ready, not connected": "La continuité Supabase est prévue dans le schéma, mais non connectée",
  "Official WebMCP docs": "Documentation WebMCP officielle",
  "Agent activity": "Activité des agents",
  "Local structured audit stream — no prompts, secrets or raw inputs are logged": "Journal d’audit structuré local — aucun prompt, secret ni contenu brut n’est enregistré",
  "Workspace tool call": "Appel d’outil de l’espace",
  "No agent calls yet": "Aucun appel d’agent pour le moment",
  "Activity appears here after a compatible browser invokes a BuildCheck site tool.": "L’activité apparaîtra ici lorsqu’un navigateur compatible invoquera un outil BuildCheck du site.",

  // Tool catalog presentation
  "Analyze an idea, persist it in the current workspace, and use an external source only with explicit allow_external_lookup consent.": "Analyser une idée, l’enregistrer dans l’espace actuel et n’utiliser une source externe qu’avec le consentement explicite allow_external_lookup.",
  "Should I build an AI CRM for freelancers?": "Devrais-je construire un CRM IA pour les freelances ?",
  "Challenge an existing project or an idea using available evidence and clearly labeled assumptions.": "Challenger un projet existant ou une idée à partir des preuves disponibles et d’hypothèses clairement identifiées.",
  "Roast project generic-ai-crm.": "Challenge le projet generic-ai-crm.",
  "Return the latest complete analysis for a project owned by the current session.": "Renvoyer la dernière analyse complète d’un projet appartenant à la session actuelle.",
  "Get my BuildCheck analysis for InvoiceFlow.": "Récupère mon analyse BuildCheck pour InvoiceFlow.",
  "Reduce a project or idea to the cheapest testable scope and machine-readable success criteria.": "Réduire un projet ou une idée au périmètre testable le moins coûteux avec des critères de réussite lisibles par machine.",
  "What is the cheapest way to validate it?": "Quel est le moyen le moins coûteux de le valider ?",
  "Return directional hour and AI-token ranges plus scope risk factors.": "Renvoyer des fourchettes indicatives d’heures et de tokens IA ainsi que les facteurs de risque du périmètre.",
  "Estimate the full build cost for RefundOps.": "Estime le coût de construction complet de RefundOps.",
  "Filter opportunities available in BuildCheck; demo mode uses the curated seed feed.": "Filtrer les opportunités disponibles dans BuildCheck ; le mode démo utilise le flux initial sélectionné.",
  "Find B2B ecommerce opportunities above 80.": "Trouve des opportunités e-commerce B2B au-dessus de 80.",
  "Advise whether a full build is justified and return a structured warning plus smaller alternative when it is not.": "Indiquer si une construction complète est justifiée et, sinon, renvoyer un avertissement structuré avec une alternative plus petite.",
  "Should I build the full product now?": "Dois-je construire le produit complet maintenant ?",
  "Roast an idea": "Challenger une idée",
  "Get project analysis": "Obtenir l’analyse du projet",
  "Generate validation MVP": "Générer le MVP de validation",
  "Estimate build cost": "Estimer le coût de construction",
  "Find opportunities": "Trouver des opportunités",
  "Evaluate before build": "Évaluer avant de construire",
  "Analyze and save an idea in the signed-in BuildCheck workspace. Returns structured scores, evidence provenance, cost ranges, risks, and the recommended minimum next action. External lookup occurs only when allow_external_lookup is explicitly true; otherwise configured sources remain mock-only.": "Analyser et enregistrer une idée dans l’espace BuildCheck connecté. Renvoie des scores structurés, la provenance des preuves, des fourchettes de coût, les risques et la prochaine action minimale recommandée. Une recherche externe n’a lieu que si allow_external_lookup vaut explicitement true ; sinon les sources configurées restent mockées.",
  "Challenge a project owned by the signed-in user or an idea supplied directly. Evidence-backed risks and hypothetical pivots are labeled separately.": "Challenger un projet appartenant à l’utilisateur connecté ou une idée fournie directement. Les risques fondés sur des preuves et les pivots hypothétiques sont identifiés séparément.",
  "Read the latest analysis for a BuildCheck project owned by the signed-in user. Unknown and unauthorized IDs return the same generic error.": "Lire la dernière analyse d’un projet BuildCheck appartenant à l’utilisateur connecté. Les identifiants inconnus et non autorisés renvoient la même erreur générique.",
  "Return the smallest testable product, explicit exclusions, success metrics and a validation sequence for a project or idea.": "Renvoyer le plus petit produit testable, les exclusions explicites, les indicateurs de réussite et une séquence de validation pour un projet ou une idée.",
  "Return directional hour and AI-token ranges. Estimates are scope heuristics, never exact usage measurements.": "Renvoyer des fourchettes indicatives d’heures et de tokens IA. Ces estimations reposent sur le périmètre et ne sont jamais des mesures d’usage exactes.",
  "Filter BuildCheck opportunities by category, audience, maximum complexity and minimum score. Results are explicitly marked as demo data.": "Filtrer les opportunités BuildCheck par catégorie, audience, complexité maximale et score minimal. Les résultats sont explicitement marqués comme données de démonstration.",
  "Run BuildCheck's pre-build guard for a project or idea. Advises rather than blocks, and returns a structured full-build warning plus a smaller alternative when needed.": "Exécuter la protection avant construction de BuildCheck pour un projet ou une idée. Elle conseille sans bloquer et renvoie, si nécessaire, un avertissement structuré contre la construction complète ainsi qu’une alternative plus petite.",
  "Explicit consent to send derived search keywords to the configured external data source.": "Consentement explicite à l’envoi de mots-clés de recherche dérivés vers la source de données externe configurée.",
  "Seven independent dimensions, weighted to exactly 100 points": "Sept dimensions indépendantes, pondérées pour totaliser exactement 100 points",
  "Top user frustrations": "Principales frustrations utilisateur",
  "Frequency is simulated from the demo discovery sample": "La fréquence est simulée à partir de l’échantillon de découverte démo",
  "mentions": "mentions",
  "Evidence, not vibes.": "Des preuves, pas des impressions.",
  "Observable signals behind the score": "Signaux observables à l’origine du score",
  "Every item below belongs to the curated demo dataset — none came from a live platform.": "Chaque élément ci-dessous appartient au jeu de données de démonstration sélectionné — aucun ne provient d’une plateforme réelle.",
  "Every item below links to the observed public discussion. Classification and scoring remain deterministic interpretations.": "Chaque élément ci-dessous renvoie à la discussion publique observée. La classification et la notation restent des interprétations déterministes.",
  "Demo fallback": "Repli sur la démo",
  "Simulated dataset": "Jeu de données simulé",
  "Observed public source": "Source publique observée",
  "signals": "signaux",
  "source groups": "groupes de sources",
  "payment signals": "signaux de paiement",
  "Observed": "Observé",
  "pain": "douleur",
  "competitor complaint": "plainte envers un concurrent",
  "churn risk": "risque d’attrition",
  "willingness to pay": "propension à payer",
  "demand": "demande",
  "workaround": "contournement",
  "market growth": "croissance du marché",
  "feature request": "demande de fonctionnalité",
  "distribution": "distribution",
  "Competitive landscape": "Paysage concurrentiel",
  "Alternatives validate the category; their repeated weaknesses define the wedge.": "Les alternatives valident la catégorie ; leurs faiblesses récurrentes définissent l’angle d’attaque.",
  "demo competitors": "concurrents de démonstration",
  "Name": "Nom",
  "Positioning": "Positionnement",
  "Pricing": "Tarification",
  "Strengths": "Forces",
  "Weaknesses": "Faiblesses",
  "Opportunity": "Opportunité",
  "Opportunity matrix": "Matrice d’opportunité",
  "Qualitative placement from this dataset, not a market-size model": "Positionnement qualitatif issu de ce jeu de données, pas d’un modèle de taille de marché",
  "HIGH COMPETITION · LOW OPPORTUNITY": "FORTE CONCURRENCE · FAIBLE OPPORTUNITÉ",
  "HIGH COMPETITION · HIGH OPPORTUNITY": "FORTE CONCURRENCE · FORTE OPPORTUNITÉ",
  "LOW COMPETITION · LOW DEMAND": "FAIBLE CONCURRENCE · FAIBLE DEMANDE",
  "LOW COMPETITION · HIGH OPPORTUNITY": "FAIBLE CONCURRENCE · FORTE OPPORTUNITÉ",
  "Feature-for-feature clone": "Clone fonctionnalité par fonctionnalité",
  "Incumbents win on breadth and distribution.": "Les acteurs établis gagnent par leur couverture et leur distribution.",
  "Focused workflow wedge": "Angle d’attaque sur un workflow ciblé",
  "Users pay already but complain about complexity and poor segment fit.": "Les utilisateurs paient déjà, mais se plaignent de la complexité et d’une mauvaise adéquation à leur segment.",
  "Category creation": "Création de catégorie",
  "Avoid until problem frequency and budget are proven.": "À éviter tant que la fréquence du problème et le budget ne sont pas prouvés.",
  "Manual-first vertical": "Verticale d’abord manuelle",
  "Best explored with a paid concierge offer.": "À explorer de préférence avec une offre de conciergerie payante.",
  "Market gap": "Espace de marché",
  "Win through a narrower operating model, not more features.": "Gagnez avec un modèle opérationnel plus ciblé, pas avec davantage de fonctionnalités.",
  "The category has alternatives, but demo evidence consistently penalizes broad setup and pricing.": "La catégorie comporte des alternatives, mais les preuves de démonstration pénalisent systématiquement la configuration lourde et les prix élevés.",
  "one vertical": "une verticale",
  "Can you actually reach these people?": "Pouvez-vous réellement atteindre ces personnes ?",
  "Distribution score": "Score de distribution",
  "A market is only useful when an early channel is specific, accessible and repeatable.": "Un marché n’est utile que si un premier canal est précis, accessible et reproductible.",
  "Best first acquisition channel": "Meilleur premier canal d’acquisition",
  "Start with conversations and paid pilots, not scale.": "Commencez par des échanges et des pilotes payants, pas par le passage à l’échelle.",
  "How to get your first 100 users": "Comment obtenir vos 100 premiers utilisateurs",
  "A proof-led sequence that begins manually": "Une séquence guidée par les preuves qui commence manuellement",
  "Do you really need to build all of this?": "Avez-vous réellement besoin de construire tout cela ?",
  "Cut scope until the riskiest assumption is exposed.": "Réduisez le périmètre jusqu’à exposer l’hypothèse la plus risquée.",
  "ORIGINAL CONCEPT": "CONCEPT ORIGINAL",
  "Potential build": "Construction potentielle",
  "MINIMUM TESTABLE VERSION": "VERSION MINIMALE TESTABLE",
  "Recommended": "Recommandé",
  "Estimated build": "Construction estimée",
  "Test hypothesis": "Hypothèse à tester",
  "Include": "Inclure",
  "Explicitly exclude": "Exclure explicitement",
  "Success criteria": "Critères de réussite",
  "Validation MVP generated": "MVP de validation généré",
  "Scope locked in this demo session. The next production step would persist it to": "Périmètre enregistré dans cette session de démonstration. La prochaine étape de production le persisterait dans",
  "Possible pivots": "Pivots possibles",
  "Narrower concepts inferred only from the supplied idea and demo evidence": "Concepts plus ciblés déduits uniquement de l’idée fournie et des preuves de démonstration",
  "Potential score": "Score potentiel",
  "Hypothetical": "Hypothétique",
  "For": "Pour",
  "What coding this concept could consume": "Ce que le code de ce concept pourrait consommer",
  "Directional engineering estimate based on scope, not an API invoice.": "Estimation d’ingénierie indicative fondée sur le périmètre, pas sur une facture d’API.",
  "AI CODING USAGE": "USAGE IA POUR LE CODE",
  "DEBUG ITERATIONS": "ITÉRATIONS DE DÉBOGAGE",
  "BUILD COMPLEXITY": "COMPLEXITÉ DE CONSTRUCTION",
  "BUILD EFFORT": "EFFORT DE CONSTRUCTION",
  "Recommendation": "Recommandation",
  "Do not spend these tokens yet.": "Ne dépensez pas encore ces tokens.",
  "Spend only enough to run the validation MVP.": "Ne dépensez que le nécessaire pour exécuter le MVP de validation.",
  "Confidence is": "La confiance est de",
  "Resolve the riskiest unknown with a test before committing to the full build.": "Levez l’inconnue la plus risquée avec un test avant de vous engager dans la construction complète.",
  "Adversarial review": "Revue contradictoire",
  "These are failure hypotheses, not invented evidence. Each one should become a cheap test.": "Ce sont des hypothèses d’échec, pas des preuves inventées. Chacune doit devenir un test peu coûteux.",
  "Reasons this could fail": "Raisons pour lesquelles cela pourrait échouer",
  "What would change our mind?": "Qu’est-ce qui nous ferait changer d’avis ?",
  "Better angle detected": "Meilleur angle détecté",
  "POTENTIAL SCORE": "SCORE POTENTIEL",
  "Immutable analysis history": "Historique d’analyse immuable",
  "Re-analysis appends a version; prior verdicts remain available.": "Chaque réanalyse ajoute une version ; les verdicts précédents restent disponibles.",
  "Project not found": "Projet introuvable",
  "This idea is not in the current demo workspace. Local demo data may have been reset.": "Cette idée ne se trouve pas dans l’espace de démonstration actuel. Les données locales ont peut-être été réinitialisées.",
  "Back to projects": "Retour aux projets",
  "Use with agent": "Utiliser avec un agent",
  "Print": "Imprimer",
  "Analyzing…": "Analyse…",
  "Re-analyze": "Réanalyser",
  "Demo evidence": "Preuves de démonstration",
  "Observed evidence": "Preuves observées",
  "Agent Ready": "Prêt pour l’agent",
  "Confidence": "Confiance",
  "Promising, but insufficient evidence.": "Prometteur, mais les preuves sont insuffisantes.",
  "Pre-build decision": "Décision avant construction",
  "the riskiest assumption": "l’hypothèse la plus risquée",
  "Generate MVP": "Générer le MVP",
  "View evidence": "Voir les preuves",
  "Ask the agent on this live page for project": "Interrogez l’agent sur cette page active à propos du projet",
  "WebMCP status": "Statut WebMCP",
  "Report sections": "Sections du rapport",
  "Next best action": "Prochaine meilleure action",
  "Open MVP plan": "Ouvrir le plan MVP",
  "Analysis ID": "ID de l’analyse",
  "Archive project": "Archiver le projet",
  // Demo projects and opportunities
  "Automate polite overdue invoice follow-ups for independent consultants without replacing their accounting software.": "Automatiser les relances courtoises de factures en retard pour les consultants indépendants sans remplacer leur logiciel comptable.",
  "Independent consultants and freelance studios": "Consultants indépendants et studios freelances",
  "independent consultants and freelance studios": "consultants indépendants et studios freelances",
  "Recover late invoices without awkward manual chasing": "Récupérer les factures en retard sans relances manuelles délicates",
  "recover late invoices without awkward manual chasing": "récupérer les factures en retard sans relances manuelles délicates",
  "€19 monthly subscription": "Abonnement mensuel à 19 €",
  "A Shopify app that tracks refund exceptions, updates customers automatically and shows support teams what needs attention.": "Une application Shopify qui suit les exceptions de remboursement, informe automatiquement les clients et indique aux équipes support les éléments nécessitant leur attention.",
  "Shopify stores with 500–5,000 monthly orders": "Boutiques Shopify réalisant 500 à 5 000 commandes mensuelles",
  "shopify stores with 500–5,000 monthly orders": "boutiques Shopify réalisant 500 à 5 000 commandes mensuelles",
  "Refund exceptions create repetitive support tickets and chargeback risk": "Les exceptions de remboursement génèrent des tickets support répétitifs et un risque de rétrofacturation",
  "refund exceptions create repetitive support tickets and chargeback risk": "les exceptions de remboursement génèrent des tickets support répétitifs et un risque de rétrofacturation",
  "$49–$99 monthly subscription": "Abonnement mensuel de 49 à 99 $",
  "North America and Europe": "Amérique du Nord et Europe",
  "A native iOS and Android AI meal planner with live grocery integrations, personalized recipes and a family dashboard.": "Un planificateur de repas IA natif iOS et Android avec intégrations courses en direct, recettes personnalisées et tableau de bord familial.",
  "Busy households": "Foyers très occupés",
  "busy households": "foyers très occupés",
  "Deciding what to cook every day": "Décider quoi cuisiner chaque jour",
  "deciding what to cook every day": "décider quoi cuisiner chaque jour",
  "$9 monthly consumer subscription": "Abonnement grand public à 9 $/mois",
  "Global": "Monde",
  "Generic AI CRM for freelancers": "CRM IA générique pour freelances",
  "Generic AI CRM for freelancers for freelancers": "CRM IA générique pour freelances",
  "A full AI-powered CRM platform for freelancers with email integrations, realtime chat, native mobile apps and automated sales pipelines.": "Une plateforme CRM complète propulsée par l’IA pour les freelances, avec intégrations e-mail, chat en temps réel, applications mobiles natives et pipelines de vente automatisés.",
  "Freelancers": "Freelances",
  "freelancers": "freelances",
  "CRM data entry takes too much time": "La saisie des données CRM prend trop de temps",
  "crm data entry takes too much time": "la saisie des données CRM prend trop de temps",
  "$29 per seat monthly": "29 $ par utilisateur et par mois",
  "Invoice follow-up and approval evidence for specialist construction subcontractors working with general contractors.": "Relance de factures et preuves d’approbation pour les sous-traitants spécialisés du bâtiment travaillant avec des entreprises générales.",
  "Construction subcontractors with five to twenty field teams": "Sous-traitants du bâtiment disposant de cinq à vingt équipes terrain",
  "construction subcontractors with five to twenty field teams": "sous-traitants du bâtiment disposant de cinq à vingt équipes terrain",
  "Recover approved invoices when payment responsibility is unclear": "Recouvrer les factures approuvées lorsque la responsabilité du paiement est floue",
  "recover approved invoices when payment responsibility is unclear": "recouvrer les factures approuvées lorsque la responsabilité du paiement est floue",
  "$79 monthly per subcontractor": "79 $ par mois et par sous-traitant",
  "United Kingdom": "Royaume-Uni",
  "Refund exception desk for small Shopify stores": "Gestion des exceptions de remboursement pour petites boutiques Shopify",
  "A focused operations layer for delayed, partial and failed refunds.": "Une couche opérationnelle ciblée pour les remboursements retardés, partiels ou échoués.",
  "Support teams cannot see which approved refunds are actually stuck.": "Les équipes support ne voient pas quels remboursements approuvés sont réellement bloqués.",
  "Shopify stores with 2–10 support agents": "Boutiques Shopify comptant 2 à 10 agents support",
  "Ecommerce": "E-commerce",
  "Compliance handover packs for solar installers": "Dossiers de conformité pour installateurs solaires",
  "Generate customer and regulator-ready evidence packs from field photos and checklists.": "Générer des dossiers de preuves prêts pour les clients et les régulateurs à partir de photos terrain et de listes de contrôle.",
  "Small installers lose hours assembling inconsistent project handovers.": "Les petits installateurs perdent des heures à assembler des dossiers de livraison de projet incohérents.",
  "Independent solar installation teams": "Équipes indépendantes d’installation solaire",
  "Productivity": "Productivité",
  "Scope-creep ledger for product agencies": "Registre des dérives de périmètre pour agences produit",
  "Turn client requests into an auditable margin and change-order workflow.": "Transformer les demandes clients en un workflow auditable de marge et d’avenants.",
  "Small agencies discover unbilled work only after project margin has disappeared.": "Les petites agences découvrent le travail non facturé seulement après la disparition de la marge du projet.",
  "Digital product agencies with 5–30 people": "Agences de produits numériques de 5 à 30 personnes",
  "Finance": "Finance",
  "Accessibility release checks for Webflow agencies": "Contrôles d’accessibilité avant livraison pour agences Webflow",
  "A client-ready preflight and remediation report built around Webflow delivery.": "Un rapport de précontrôle et de correction prêt pour le client, conçu autour des livraisons Webflow.",
  "Agencies run generic audits but struggle to turn results into scoped fixes before launch.": "Les agences réalisent des audits génériques mais peinent à transformer les résultats en corrections cadrées avant le lancement.",
  "Webflow design and development agencies": "Agences de design et de développement Webflow",
  // Generated report language
  "Willingness to pay": "Propension à payer",
  "Competition gap": "Espace concurrentiel",
  "Build simplicity": "Simplicité de construction",
  "Defensibility": "Défendabilité",
  "Several independent signals point to repeated demand or active workarounds.": "Plusieurs signaux indépendants indiquent une demande récurrente ou des contournements actifs.",
  "Demand is plausible, but the current evidence base is still thin.": "La demande est plausible, mais les preuves actuelles restent limitées.",
  "Users describe a recurring, costly frustration in concrete terms.": "Les utilisateurs décrivent concrètement une frustration récurrente et coûteuse.",
  "The problem is visible, but urgency and frequency need direct validation.": "Le problème est visible, mais son urgence et sa fréquence doivent être validées directement.",
  "Payment language and existing paid alternatives support monetization.": "Le vocabulaire lié au paiement et les alternatives payantes existantes soutiennent la monétisation.",
  "Paid competitors help, but explicit willingness-to-pay evidence is limited.": "Les concurrents payants sont un indice, mais les preuves explicites de propension à payer restent limitées.",
  "No clearly concentrated acquisition channel has been proven yet.": "Aucun canal d’acquisition clairement concentré n’a encore été prouvé.",
  "No competitor dataset is available, so the apparent gap is low confidence.": "Aucun jeu de données concurrentiel n’est disponible ; l’espace apparent est donc peu fiable.",
  "A specific audience creates room for proprietary workflow data and positioning.": "Une audience précise ouvre la voie à des données de workflow et à un positionnement propriétaires.",
  "The idea needs a narrower wedge or compounding advantage to resist imitation.": "L’idée a besoin d’un angle plus ciblé ou d’un avantage cumulatif pour résister à l’imitation.",
  "external integration": "intégration externe",
  "external integrations": "intégrations externes",
  "payment lifecycle": "cycle de paiement",
  "realtime state": "état en temps réel",
  "native mobile delivery": "livraison mobile native",
  "AI workflow": "workflow IA",
  "AI workflows": "workflows IA",
  "standard product workflow": "workflow produit standard",
  "Not enough evidence.": "Pas assez de preuves.",
  "A narrowly defined early-adopter segment": "Un segment étroitement défini d’utilisateurs pionniers",
  "a narrowly defined early-adopter segment": "un segment étroitement défini d’utilisateurs pionniers",
  "Subscription to validate": "Abonnement à valider",
  "Untitled idea": "Idée sans titre",
  "CRM for independent property photographers": "CRM pour photographes immobiliers indépendants",
  "Independent property photographers managing estate-agent relationships": "Photographes immobiliers indépendants gérant leurs relations avec les agences immobilières",
  "A repeatable job, recognizable workflow and concentrated professional niche create a testable wedge.": "Une tâche récurrente, un workflow reconnaissable et une niche professionnelle concentrée créent un angle testable.",
  "Hypothetical vertical workflow, not another horizontal CRM. Requires its own evidence analysis.": "Workflow vertical hypothétique, pas un autre CRM horizontal. Nécessite sa propre analyse de preuves.",
  "Client follow-up concierge for one freelance vertical": "Conciergerie de suivi client pour une verticale freelance",
  "Freelancers who lose repeat business because follow-ups fall through": "Freelances qui perdent des missions récurrentes faute de suivi",
  "A manual outcome test avoids migration and full CRM scope.": "Un test manuel du résultat évite la migration et le périmètre complet d’un CRM.",
  "Prove follow-up value before storing the complete customer record.": "Prouver la valeur du suivi avant de stocker l’intégralité du dossier client.",
  "Independent operators in one high-frequency vertical": "Indépendants d’une verticale à forte fréquence",
  "A manual-first service tests urgency before platform investment.": "Un service d’abord manuel teste l’urgence avant l’investissement dans une plateforme.",
  "Sell the outcome first; automate only the repeated steps.": "Vendre d’abord le résultat ; n’automatiser que les étapes récurrentes.",
  "Existing spend creates a clearer switching and pricing benchmark.": "Les dépenses existantes fournissent un repère plus clair pour le changement et la tarification.",
  "Replace a proven budget line instead of creating a new category.": "Remplacer une ligne budgétaire éprouvée plutôt que créer une nouvelle catégorie.",
  "Evidence collection only": "Collecte de preuves uniquement",
  "10 problem interviews": "10 entretiens sur le problème",
  "A falsifiable problem statement": "Un énoncé de problème réfutable",
  "Application code": "Code applicatif",
  "Automations": "Automatisations",
  "Integrations": "Intégrations",
  "Not enough evidence to define a paid-product hypothesis.": "Pas assez de preuves pour définir une hypothèse de produit payant.",
  "At least 5 people describe the problem unprompted": "Au moins 5 personnes décrivent spontanément le problème",
  "At least 2 already pay or use a costly workaround": "Au moins 2 paient déjà ou utilisent un contournement coûteux",
  "3–5 hours": "3 à 5 heures",
  "Concierge validation MVP": "MVP de validation en conciergerie",
  "Paid pilot checkout": "Paiement de pilote payant",
  "Short onboarding form": "Court formulaire d’onboarding",
  "Manual outcome delivery": "Livraison manuelle du résultat",
  "Multi-role dashboard": "Tableau de bord multi-rôles",
  "Automated integrations": "Intégrations automatisées",
  "Native app": "Application native",
  "Advanced AI orchestration": "Orchestration IA avancée",
  "100 qualified visits": "100 visites qualifiées",
  "10 intent signups": "10 inscriptions d’intention",
  "2 repeat-use requests": "2 demandes d’usage répété",
  "4–6 hours": "4 à 6 heures",
  "There is no evidence dataset to challenge this idea yet.": "Il n’existe pas encore de jeu de preuves permettant de challenger cette idée.",
  "Collect direct problem interviews and proof of an existing workaround.": "Recueillir des entretiens directs sur le problème et la preuve d’un contournement existant.",
  "Start with one audience, one painful job, and one measurable outcome.": "Commencer par une audience, une tâche douloureuse et un résultat mesurable.",
  "The target user may tolerate the current workaround because switching is harder than the pain.": "L’utilisateur cible peut tolérer le contournement actuel car changer est plus difficile que supporter la douleur.",
  "A broad promise will compete with flexible general-purpose AI tools.": "Une promesse trop large sera en concurrence avec des outils IA généralistes et flexibles.",
  "Acquisition could cost more than the first year of gross margin.": "L’acquisition pourrait coûter plus que la marge brute de la première année.",
  "The problem may be urgent only a few times per year.": "Le problème peut n’être urgent que quelques fois par an.",
  "Incumbents can copy surface-level AI features quickly.": "Les acteurs établis peuvent rapidement copier les fonctionnalités IA superficielles.",
  "Three prospects prepay for a narrow outcome.": "Trois prospects prépaient pour un résultat ciblé.",
  "Weekly usage is observed in a manual pilot.": "Un usage hebdomadaire est observé dans un pilote manuel.",
  "One concentrated channel produces qualified conversations repeatedly.": "Un canal concentré génère régulièrement des échanges qualifiés.",
  "Users share data or workflow context that improves the product over time.": "Les utilisateurs partagent des données ou du contexte de workflow qui améliorent le produit dans le temps.",
  "CRM for independent property photographers — hypothetical until separately validated.": "CRM pour photographes immobiliers indépendants — hypothétique jusqu’à validation séparée.",
  "Offer 5 paid concierge pilots with a narrow, measurable outcome.": "Proposer 5 pilotes de conciergerie payants avec un résultat ciblé et mesurable.",
  "Ask every successful pilot for two peer introductions; keep the first cohort intentionally small.": "Demander à chaque pilote réussi deux mises en relation avec des pairs ; garder volontairement la première cohorte réduite.",
  "Automate only the step that appears in at least 4 of the 5 paid pilots.": "N’automatiser que l’étape présente dans au moins 4 des 5 pilotes payants.",
  // Curated evidence sources
  "Demo interview": "Entretien démo",
  "Demo community sample": "Échantillon de communauté démo",
  "Demo pricing study": "Étude de prix démo",
  "Demo competitor review": "Analyse concurrentielle démo",
  "Demo search sample": "Échantillon de recherche démo",
  "Demo channel map": "Cartographie de canaux démo",
  "Demo trend sample": "Échantillon de tendance démo",
  "Demo merchant interview": "Entretien commerçant démo",
  "Demo app review": "Avis d’application démo",
  "Demo workflow sample": "Échantillon de workflow démo",
  "Demo ecosystem map": "Cartographie d’écosystème démo",
  "Demo partner interview": "Entretien partenaire démo",
  "Demo consumer interview": "Entretien consommateur démo",
  "Demo social sample": "Échantillon social démo",
  "Demo founder interview": "Entretien fondateur démo",
  "Demo migration interview": "Entretien migration démo",
  "Demo buyer panel": "Panel d’acheteurs démo",
  "Demo discovery interview": "Entretien de découverte démo",

  // Invoice evidence
  "Late payments consume billable time": "Les retards de paiement consomment du temps facturable",
  "Freelancers describe repeated follow-ups as emotionally draining and easy to postpone.": "Les freelances décrivent les relances répétées comme émotionnellement épuisantes et faciles à repousser.",
  "Spreadsheet plus calendar reminders": "Tableur et rappels de calendrier",
  "The common workaround combines a spreadsheet, email templates and manual reminders.": "Le contournement habituel combine un tableur, des modèles d’e-mail et des rappels manuels.",
  "Existing spend around receivables": "Dépenses existantes autour du recouvrement",
  "Several sampled businesses already pay for accounting tools but still handle reminders manually.": "Plusieurs entreprises de l’échantillon paient déjà des outils comptables mais gèrent encore les relances manuellement.",
  "Accounting suites feel oversized": "Les suites comptables paraissent surdimensionnées",
  "Users want follow-up automation without migrating their complete bookkeeping workflow.": "Les utilisateurs veulent automatiser les relances sans migrer tout leur workflow comptable.",
  "Recurring intent around overdue invoices": "Intention récurrente autour des factures en retard",
  "Problem-aware searches focus on reducing payment delay and awkward client conversations.": "Les recherches conscientes du problème visent à réduire les délais de paiement et les conversations délicates avec les clients.",
  "Freelancer communities are concentrated": "Les communautés de freelances sont concentrées",
  "Professional communities and accountant partnerships provide identifiable access points.": "Les communautés professionnelles et les partenariats avec des comptables offrent des points d’accès identifiables.",
  "Tone-aware reminders": "Relances adaptées au ton",
  "Users ask for reminders that become firmer without damaging the client relationship.": "Les utilisateurs demandent des relances qui se raffermissent sans nuire à la relation client.",
  "Outcome-linked pricing resonates": "La tarification liée au résultat trouve un écho",
  "A small monthly fee feels reasonable when positioned against days-sales-outstanding.": "Un faible montant mensuel paraît raisonnable lorsqu’il est comparé au délai moyen de paiement.",
  "Setup complexity causes abandonment": "La complexité de configuration entraîne l’abandon",
  "People stop using broad finance suites when automation requires too much configuration.": "Les utilisateurs abandonnent les suites financières généralistes lorsque l’automatisation exige trop de configuration.",
  "Independent work remains a large niche": "Le travail indépendant reste une grande niche",
  "A large base of solo operators makes the segment testable across multiple verticals.": "Une large base d’indépendants rend le segment testable dans plusieurs verticales.",

  // Refund evidence
  "Refund status creates support load": "Le statut des remboursements alourdit le support",
  "Small merchants repeatedly answer where-is-my-refund tickets across several systems.": "Les petits commerçants répondent sans cesse aux demandes « où est mon remboursement ? » dans plusieurs systèmes.",
  "Return suites price for larger brands": "Les suites de retours tarifent pour les grandes marques",
  "Small stores describe current tooling as expensive and operationally heavy.": "Les petites boutiques décrivent les outils actuels comme coûteux et lourds à exploiter.",
  "Shared sheets coordinate exceptions": "Des feuilles partagées coordonnent les exceptions",
  "Teams export orders and track refund exceptions in shared spreadsheets.": "Les équipes exportent les commandes et suivent les exceptions de remboursement dans des tableurs partagés.",
  "Support savings create a budget": "Les économies de support créent un budget",
  "Merchants compare tooling cost with support hours and chargeback risk.": "Les commerçants comparent le coût de l’outil aux heures de support et au risque de rétrofacturation.",
  "Shopify ecosystem is concentrated": "L’écosystème Shopify est concentré",
  "App listings, agencies and merchant communities can reach a defined audience.": "Les listings d’applications, les agences et les communautés de commerçants permettent d’atteindre une audience définie.",
  "Refund automation intent": "Intention d’automatiser les remboursements",
  "Queries cluster around refund status, return exceptions and customer notifications.": "Les requêtes se concentrent sur le statut des remboursements, les exceptions de retour et les notifications clients.",
  "Proactive customer updates": "Informations clients proactives",
  "Merchants ask for branded status pages and automatic exception alerts.": "Les commerçants demandent des pages de statut à leur marque et des alertes automatiques sur les exceptions.",
  "Agencies see the pain repeatedly": "Les agences constatent régulièrement la douleur",
  "Implementation agencies can identify stores with rising support volume.": "Les agences d’implémentation peuvent identifier les boutiques dont le volume de support augmente.",
  "Complex setup weakens retention": "Une configuration complexe affaiblit la rétention",
  "Smaller merchants churn when tools require enterprise-style workflow configuration.": "Les petits commerçants abandonnent lorsque les outils imposent une configuration de workflow digne d’une grande entreprise.",
  "Post-purchase operations matter more": "Les opérations après achat gagnent en importance",
  "Retention pressure increases attention on the experience after checkout.": "La pression sur la rétention renforce l’attention portée à l’expérience après paiement.",

  // Meal and CRM evidence
  "Planning fatigue is real": "La fatigue de planification est réelle",
  "People dislike deciding what to cook, but the frustration is often short-lived.": "Les gens n’aiment pas décider quoi cuisiner, mais la frustration est souvent brève.",
  "Recommendations become repetitive": "Les recommandations deviennent répétitives",
  "Users complain that generic plans ignore household preferences after initial setup.": "Les utilisateurs se plaignent que les plans génériques ignorent les préférences du foyer après la configuration initiale.",
  "General AI is the free workaround": "L’IA généraliste est le contournement gratuit",
  "Consumers already ask general-purpose assistants for meal plans at no incremental cost.": "Les consommateurs demandent déjà des menus à des assistants généralistes sans coût supplémentaire.",
  "Subscription resistance": "Résistance à l’abonnement",
  "Sampled users expect planning to be bundled with grocery, fitness or recipe products.": "Les utilisateurs de l’échantillon s’attendent à ce que la planification soit incluse dans des produits de courses, fitness ou recettes.",
  "High interest, weak purchase intent": "Fort intérêt, faible intention d’achat",
  "Meal-plan content attracts attention but rarely contains explicit buying language.": "Les contenus de menus attirent l’attention mais comportent rarement un langage d’achat explicite.",
  "Creator channels are crowded": "Les canaux de créateurs sont saturés",
  "Food creators offer reach, but paid acquisition competes with abundant free content.": "Les créateurs culinaires offrent de la portée, mais l’acquisition payante concurrence une abondance de contenu gratuit.",
  "Novelty wears off quickly": "L’effet de nouveauté disparaît vite",
  "Reviews describe strong first-week use followed by declining engagement.": "Les avis décrivent un usage fort la première semaine, puis une baisse de l’engagement.",
  "CRM upkeep feels like admin": "La tenue du CRM ressemble à de l’administratif",
  "Teams dislike manual data entry but disagree on the workflow that should replace it.": "Les équipes détestent la saisie manuelle mais ne s’accordent pas sur le workflow qui devrait la remplacer.",
  "Incumbents are complex": "Les acteurs établis sont complexes",
  "Users repeatedly criticize configuration overhead and seat-based pricing.": "Les utilisateurs critiquent régulièrement la lourdeur de configuration et la tarification par utilisateur.",
  "Spreadsheets remain flexible": "Les tableurs restent flexibles",
  "Small teams return to spreadsheets when the CRM process becomes rigid.": "Les petites équipes reviennent aux tableurs lorsque le processus CRM devient rigide.",
  "Budget exists but switching is costly": "Le budget existe mais changer coûte cher",
  "CRM is a proven spend category, though migration risk reduces purchase intent.": "Le CRM est une catégorie de dépense éprouvée, même si le risque de migration réduit l’intention d’achat.",
  "Large established category": "Grande catégorie établie",
  "The category has demand, but generic positioning captures little solution-specific intent.": "La catégorie bénéficie d’une demande, mais un positionnement générique capte peu d’intention liée à une solution précise.",
  "Audience definition is too broad": "La définition de l’audience est trop large",
  "Nearly every business is a possible buyer, leaving no efficient first channel.": "Presque toute entreprise est un acheteur potentiel, ce qui ne laisse aucun premier canal efficace.",
  "Data migration blocks switching": "La migration des données bloque le changement",
  "Even unhappy teams hesitate when history and integrations live in the incumbent.": "Même les équipes insatisfaites hésitent lorsque leur historique et leurs intégrations résident chez l’acteur en place.",
  "Switching incentive is weak": "L’incitation au changement est faible",
  "The cost of cleaning and migrating contact history outweighs incremental AI convenience.": "Le coût du nettoyage et de la migration de l’historique des contacts dépasse le gain marginal apporté par l’IA.",
  "AI is becoming table stakes": "L’IA devient un prérequis",
  "Buyers expect automation from existing CRM vendors and do not view it as a standalone reason to switch.": "Les acheteurs attendent de l’automatisation de la part de leurs fournisseurs CRM actuels et n’y voient pas une raison suffisante de changer.",
  // Distribution channels
  "Freelancer communities": "Communautés de freelances",
  "12 focused communities": "12 communautés ciblées",
  "The job title and pain are both explicit.": "Le métier et la douleur sont tous deux explicites.",
  "Accountant partnerships": "Partenariats avec des comptables",
  "Trusted referral path": "Canal de recommandation de confiance",
  "Accountants observe late-payment pain repeatedly.": "Les comptables observent régulièrement la douleur liée aux retards de paiement.",
  "24 problem-aware topics": "24 sujets conscients du problème",
  "Intent exists but content competition is mature.": "L’intention existe mais la concurrence de contenu est mature.",
  "Role-based targeting": "Ciblage par fonction",
  "Useful for interviews and founder-led sales.": "Utile pour les entretiens et la vente menée par le fondateur.",
  "High-intent marketplace": "Place de marché à forte intention",
  "Merchants search where they already manage the store.": "Les commerçants cherchent là où ils gèrent déjà leur boutique.",
  "Ecommerce agencies": "Agences e-commerce",
  "Repeat referral channel": "Canal de recommandation récurrent",
  "Agencies see the same operational issue across clients.": "Les agences constatent le même problème opérationnel chez plusieurs clients.",
  "Merchant communities": "Communautés de commerçants",
  "9 focused groups": "9 groupes ciblés",
  "Good for discovery, with promotion constraints.": "Adapté à la découverte, avec des contraintes de promotion.",
  "18 operational keywords": "18 mots-clés opérationnels",
  "Queries reveal active implementation intent.": "Les requêtes révèlent une intention active d’implémentation.",
  "Creator partnerships": "Partenariats avec des créateurs",
  "Crowded attention market": "Marché de l’attention saturé",
  "Reach is available but trust is creator-owned.": "La portée est disponible mais la confiance appartient au créateur.",
  "App marketplaces": "Places de marché d’applications",
  "Heavy category competition": "Forte concurrence dans la catégorie",
  "Generic discovery is expensive and undifferentiated.": "La découverte générique est coûteuse et indifférenciée.",
  "Free content dominates": "Le contenu gratuit domine",
  "High volume does not imply paid intent.": "Un volume élevé n’implique pas une intention de payer.",
  "Large reachable audience": "Large audience accessible",
  "Targeting is possible but competitive and expensive.": "Le ciblage est possible mais concurrentiel et coûteux.",
  "Incumbent-dominated results": "Résultats dominés par les acteurs établis",
  "Generic CRM terms have weak entry economics.": "Les termes CRM génériques offrent une économie d’entrée faible.",
  "Vertical partnerships": "Partenariats verticaux",
  "No vertical selected": "Aucune verticale sélectionnée",
  "A niche is required before this channel becomes usable.": "Une niche est nécessaire avant que ce canal ne devienne exploitable.",
  "Focused community": "Communauté ciblée",
  "1 initial test channel": "1 canal de test initial",
  "Enough for interviews and a concierge pilot, not yet scalable.": "Suffisant pour des entretiens et un pilote de conciergerie, pas encore pour passer à l’échelle.",
  "Founder-led outreach": "Prospection menée par le fondateur",
  "Manual first conversations": "Premiers échanges manuels",
  "Direct learning is more valuable than broad reach at this stage.": "À ce stade, l’apprentissage direct vaut davantage qu’une large portée.",

  // Competitor records
  "All-in-one small-business accounting": "Comptabilité tout-en-un pour petites entreprises",
  "Small businesses": "Petites entreprises",
  "small businesses": "petites entreprises",
  "Trusted finance workflow": "Workflow financier de confiance",
  "Broad integrations": "Intégrations étendues",
  "Heavy setup": "Configuration lourde",
  "Follow-up is secondary": "Les relances sont secondaires",
  "Own the freelancer-specific collection workflow.": "S’approprier le workflow de recouvrement propre aux freelances.",
  "Accounts-receivable automation": "Automatisation des comptes clients",
  "Finance teams": "Équipes financières",
  "finance teams": "équipes financières",
  "Deep automation": "Automatisation avancée",
  "Too expensive for solos": "Trop coûteux pour les indépendants",
  "Finance-team language": "Langage destiné aux équipes financières",
  "Simplify onboarding and price around solo cash flow.": "Simplifier l’onboarding et tarifer selon la trésorerie des indépendants.",
  "Enterprise returns management": "Gestion des retours pour entreprises",
  "Mid-market retailers": "Commerçants de taille intermédiaire",
  "mid-market retailers": "commerçants de taille intermédiaire",
  "Full returns lifecycle": "Cycle complet des retours",
  "Complex": "Complexe",
  "Expensive for small stores": "Coûteux pour les petites boutiques",
  "Focus only on refund exceptions and communication.": "Se concentrer uniquement sur les exceptions de remboursement et la communication.",
  "Order-status support automation": "Automatisation du support sur le statut des commandes",
  "Online stores": "Boutiques en ligne",
  "online stores": "boutiques en ligne",
  "Customer-facing portal": "Portail orienté client",
  "Weak exception workflow": "Workflow d’exceptions insuffisant",
  "Become the operational layer after approval.": "Devenir la couche opérationnelle après approbation.",
  "Flexible free-form assistant": "Assistant flexible en langage libre",
  "Free": "Gratuit",
  "Everyone": "Tout le monde",
  "everyone": "tout le monde",
  "Flexible": "Flexible",
  "Already adopted": "Déjà adopté",
  "Low continuity": "Faible continuité",
  "No specialist workflow": "Aucun workflow spécialisé",
  "A narrow clinical or performance niche only.": "Uniquement une niche clinique ou de performance ciblée.",
  "Recipes and weekly plans": "Recettes et menus hebdomadaires",
  "Households": "Foyers",
  "households": "foyers",
  "Large recipe catalog": "Grand catalogue de recettes",
  "Low personalization": "Faible personnalisation",
  "Avoid the generic household market.": "Éviter le marché générique des foyers.",
  "Training and nutrition bundle": "Offre groupée entraînement et nutrition",
  "Fitness consumers": "Pratiquants de fitness",
  "fitness consumers": "pratiquants de fitness",
  "Habit loop": "Boucle d’habitude",
  "Bundled value": "Valeur groupée",
  "Generic food guidance": "Conseils alimentaires génériques",
  "Serve one professional performance workflow.": "Servir un seul workflow de performance professionnelle.",
  "Horizontal sales platform": "Plateforme de vente horizontale",
  "Sales teams": "Équipes commerciales",
  "sales teams": "équipes commerciales",
  "Ecosystem": "Écosystème",
  "Expensive": "Coûteux",
  "Requires a vertical workflow wedge.": "Nécessite un angle d’attaque sur un workflow vertical.",
  "Lightweight pipeline": "Pipeline léger",
  "Small teams": "Petites équipes",
  "small teams": "petites équipes",
  "Easy adoption": "Adoption facile",
  "Limited vertical depth": "Profondeur verticale limitée",
  "Compete on a specific job, not simplicity alone.": "Concurrencer sur une tâche précise, pas uniquement sur la simplicité.",
  "Flexible DIY tracking": "Suivi flexible à faire soi-même",
  "Small operators": "Petits opérateurs",
  "small operators": "petits opérateurs",
  "Familiar": "Familier",
  "Manual": "Manuel",
  "No process guidance": "Aucun guidage de processus",
  "Automate one painful repeated update.": "Automatiser une mise à jour répétitive et douloureuse.",
  "Problem mentioned without urgency": "Problème mentionné sans urgence",
  "The target user recognizes the issue but has not quantified its cost or frequency.": "L’utilisateur cible reconnaît le problème mais n’en a quantifié ni le coût ni la fréquence.",
  "Manual workaround exists": "Un contournement manuel existe",
  "People combine familiar tools instead of buying a dedicated product.": "Les utilisateurs combinent des outils familiers au lieu d’acheter un produit dédié.",
  "Budget remains unproven": "Le budget reste à prouver",
  "No sampled user made an explicit commitment to pay yet.": "Aucun utilisateur de l’échantillon ne s’est encore explicitement engagé à payer.",
  "Some problem-aware interest": "Un certain intérêt conscient du problème",
  "Search intent exists, but it mixes educational and product-seeking behavior.": "L’intention de recherche existe mais mêle comportements éducatifs et recherche de produit.",
  "One testable community": "Une communauté testable",
  "A focused community offers a place to run interviews and a manual pilot.": "Une communauté ciblée offre un espace pour mener des entretiens et un pilote manuel.",
  "Alternatives have minor gaps": "Les alternatives présentent des lacunes mineures",
  "Complaints exist but do not yet reveal a strong switching trigger.": "Des plaintes existent mais ne révèlent pas encore de déclencheur fort de changement.",
  "Existing workflow": "Workflow existant",
  "Familiar combination of tools": "Combinaison d’outils familiers",
  "Current target segment": "Segment cible actuel",
  "Manual handoffs": "Passages de relais manuels",
  "Prove one handoff is painful enough to replace.": "Prouver qu’un passage de relais est assez douloureux pour être remplacé.",
  "Mock sources · curated scenarios": "Sources mockées · scénarios sélectionnés",
  "Mock AI · deterministic": "IA mockée · déterministe",
  "Mock AI": "IA mockée",
  "Curated demo evidence; no live market source was queried.": "Preuves de démonstration sélectionnées ; aucune source marché réelle n’a été interrogée."
};

function translateFrench(text: string): string {
  const exact = french[text];
  if (exact) return exact;
  const replacements: Array<[RegExp, (...parts: string[]) => string]> = [
    [/^Good morning, (.+)\.$/, (name) => `Bonjour, ${name}.`],
    [/^(\d+) mentions$/, (count) => `${count} mentions`],
    [/^(\d+) signals$/, (count) => `${count} signaux`],
    [/^(\d+) site tools available$/, (count) => `${count} outils du site disponibles`],
    [/^Analysis v(\d+)$/, (version) => `Analyse v${version}`],
    [/^Project (.+)$/, (id) => `Projet ${id}`],
    [/^(.+) has (\d+) demo signals across (\d+) evidence types, including (\d+) strong indicators\. Treat this as a product walkthrough until real sources confirm the pattern\.$/, (name, signals, types, strong) => `${translateFrench(name)} dispose de ${signals} signaux de démonstration couvrant ${types} types de preuves, dont ${strong} indicateurs forts. Considérez ceci comme une présentation produit tant que des sources réelles ne confirment pas cette tendance.`],
    [/^(.+) has (\d+) observed public-source signals across (\d+) evidence types, including (\d+) strong indicators\. Treat anecdotal discussions as directional evidence, not representative market research\.$/, (name, signals, types, strong) => `${translateFrench(name)} dispose de ${signals} signaux observés dans des sources publiques couvrant ${types} types de preuves, dont ${strong} indicateurs forts. Considérez les discussions anecdotiques comme des indices, pas comme une étude de marché représentative.`],
    [/^(.+) will pay for a faster way to (.+)\.$/, (audience, problem) => `${translateFrench(audience)} paiera pour un moyen plus rapide de ${translateFrench(problem)}.`],
    [/^(.+) for teams with an existing paid workflow$/, (name) => `${translateFrench(name)} pour les équipes disposant déjà d’un workflow payant`],
    [/^(.+) for (.+), delivered as a measurable outcome rather than another dashboard\.$/, (name, audience) => `${translateFrench(name)} pour ${translateFrench(audience)}, livré comme un résultat mesurable plutôt que comme un tableau de bord supplémentaire.`],
    [/^(.+) for (.+)$/, (name, audience) => `${translateFrench(name)} pour ${translateFrench(audience)}`],
    [/^(.+) Concierge$/, (name) => `Conciergerie ${translateFrench(name)}`],
    [/^Small teams already paying to solve (.+)$/, (problem) => `Petites équipes qui paient déjà pour résoudre ${translateFrench(problem)}`],
    [/^(\d+) channel(s?) offers concentrated access to the target audience\.$/, (count) => `${count} ${count === "1" ? "canal offre" : "canaux offrent"} un accès concentré à l’audience cible.`],
    [/^(\d+) alternatives validate the category; recurring weaknesses create a possible wedge\.$/, (count) => `${count} alternatives valident la catégorie ; leurs faiblesses récurrentes créent un angle d’attaque possible.`],
    [/^(Low|Medium|High|Very high) implementation complexity, driven by (.+)\.$/, (level, drivers) => `Complexité d’implémentation ${translateFrench(level).toLowerCase()}, principalement due à : ${drivers.split(", ").map(translateFrench).join(", ")}.`],
    [/^Interview 10 prospects through (.+); record current workflow, frequency and cost\.$/, (channel) => `Interroger 10 prospects via ${translateFrench(channel)} ; documenter leur workflow actuel, sa fréquence et son coût.`],
    [/^Turn the strongest proof into a before\/after case study(?: and distribute it through (.+))?\.$/, (channel) => `Transformer la preuve la plus forte en étude de cas avant/après${channel ? ` et la diffuser via ${translateFrench(channel)}` : ""}.`],
    [/^\$(.+)\/mo$/, (price) => `$${price}/mois`],
    [/^\$(.+)\/seat$/, (price) => `$${price}/utilisateur`],
    [/^(\d+) external integrations$/, (count) => `${count} intégrations externes`],
    [/^(\d+) AI workflow(s?)$/, (count) => `${count} workflow${count === "1" ? "" : "s"} IA`]
  ];
  for (const [pattern, replacement] of replacements) {
    const match = text.match(pattern);
    if (match) return replacement(...match.slice(1));
  }
  return text;
}

export function translateText(source: string, locale: Locale): string {
  return locale === "fr" ? translateFrench(source) : source;
}

interface LanguageValue {
  locale: Locale;
  localeCode: "en-US" | "fr-FR";
  setLocale: (locale: Locale) => void;
  t: (source: string) => string;
}

const LanguageContext = createContext<LanguageValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("en");
  const pathname = usePathname();

  useEffect(() => {
    const stored = window.localStorage.getItem(STORAGE_KEY);
    const next = stored === "fr" ? "fr" : "en";
    document.documentElement.lang = next;
    queueMicrotask(() => setLocaleState(next));
  }, []);

  useEffect(() => {
    const title = pathname === "/" ? "Stop building SaaS nobody wants"
      : pathname === "/login" ? "Sign in"
        : pathname === "/signup" ? "Create account"
          : pathname === "/forgot-password" ? "Reset password"
            : pathname === "/onboarding" ? "Onboarding"
              : pathname === "/methodology" ? "Methodology"
                : pathname.startsWith("/projects/") ? "Project analysis"
                  : pathname.slice(1).split("/")[0]?.replace(/^./, (letter) => letter.toUpperCase()) || "BuildCheck";
    const desiredTitle = pathname === "/" ? `BuildCheck — ${translateText(title, locale)}` : `${translateText(title, locale)} · BuildCheck`;
    const syncTitle = () => {
      if (document.title !== desiredTitle) document.title = desiredTitle;
    };
    syncTitle();
    const observer = new MutationObserver(syncTitle);
    observer.observe(document.head, { childList: true, subtree: true, characterData: true });
    return () => observer.disconnect();
  }, [locale, pathname]);

  const setLocale = useCallback((next: Locale) => {
    setLocaleState(next);
    window.localStorage.setItem(STORAGE_KEY, next);
    document.documentElement.lang = next;
  }, []);

  const t = useCallback((source: string) => {
    return translateText(source, locale);
  }, [locale]);

  const value = useMemo<LanguageValue>(() => ({
    locale,
    localeCode: locale === "fr" ? "fr-FR" : "en-US",
    setLocale,
    t
  }), [locale, setLocale, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used inside LanguageProvider");
  return value;
}
